import { createWorkspaceDomain, type Workspace, type Project, type WorkspaceDomain, type WorkspaceStore } from '../dist/index.js';

declare const store: WorkspaceStore;
const domain: WorkspaceDomain = createWorkspaceDomain({ store });
async function contract() {
  const w: Workspace = await domain.createWorkspace({ name: 'Example' });
  const p: Project = await domain.createProject({ workspaceId: w.id, name: 'Example project' });
  await domain.getWorkspace({ id: w.id });
  await domain.getProject({ id: p.id });
  await domain.listProjects({ workspaceId: w.id });
  // @ts-expect-error Projects cannot be created without a Workspace.
  await domain.createProject({ name: 'No parent' });
  // @ts-expect-error Product identity is not a filesystem cwd.
  await domain.createWorkspace({ name: 'Example', cwd: '/tmp' });
  // @ts-expect-error IDs are generated by the domain.
  await domain.createWorkspace({ name: 'Example', id: 'chosen' });
  // @ts-expect-error Project ownership is immutable in v0.
  p.workspaceId = w.id;
  // @ts-expect-error Entity queries require an explicit ID, not a name/cwd.
  await domain.getProject({ name: 'Example project' });
}
void contract;
